services:
  - type: web
    name: emotion-book-recommender
    runtime: python
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn flask_emotion_books:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
